/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import sistema.de.gerenciamento.de.farmácia.DAOProduto;
import sistema.de.gerenciamento.de.farmácia.Produto;

/**
 *
 * @author LuizHenrique
 */
public class formProduto extends javax.swing.JFrame {

    /**
     * Creates new form formProduto
     */
    public formProduto() {
        initComponents();
        resetText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloProduto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nomeProduto = new javax.swing.JTextField();
        buscarProduto = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        codigoProduto = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        fabricanteProduto = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        precoProduto = new javax.swing.JTextField();
        salvarProduto = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        atualizarProduto = new javax.swing.JButton();
        excluirProduto = new javax.swing.JButton();
        exit = new javax.swing.JButton();

        setTitle("CADASTRO DO PRODUTO");

        tituloProduto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tituloProduto.setText("CADASTRO DO PRODUTO");

        jLabel1.setText("Nome");

        buscarProduto.setText("Buscar");
        buscarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarProdutoActionPerformed(evt);
            }
        });

        jLabel8.setText("Código");

        jLabel12.setText("Fabricante");

        jLabel13.setText("Preço");

        salvarProduto.setText("Salvar");
        salvarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarProdutoActionPerformed(evt);
            }
        });

        reset.setText("Limpar");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        atualizarProduto.setText("Atualizar");
        atualizarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarProdutoActionPerformed(evt);
            }
        });

        excluirProduto.setText("Excluir");
        excluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirProdutoActionPerformed(evt);
            }
        });

        exit.setText("Voltar");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(salvarProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(atualizarProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(excluirProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reset)
                        .addGap(70, 70, 70)
                        .addComponent(exit))
                    .addComponent(tituloProduto)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel12)
                            .addComponent(jLabel8)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(precoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(codigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(buscarProduto))
                                .addComponent(nomeProduto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                                .addComponent(fabricanteProduto, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(tituloProduto)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(codigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(fabricanteProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarProduto)
                    .addComponent(atualizarProduto)
                    .addComponent(excluirProduto)
                    .addComponent(exit)
                    .addComponent(reset))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarProdutoActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(codigoProduto.getText());
        Produto buscar = buscarProduto(id);
        nomeProduto.setText(buscar.getNomeProduto());
        codigoProduto.setText(String.valueOf(buscar.getIdProduto()));
        precoProduto.setText(String.valueOf(buscar.getPrecoProduto()));
        fabricanteProduto.setText(String.valueOf(buscar.getFabricanteProduto()));
        
    }//GEN-LAST:event_buscarProdutoActionPerformed

    private void salvarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarProdutoActionPerformed
        // TODO add your handling code here:
        Produto novoProduto = null;
        
        DAOProduto daoProduto = new DAOProduto();
        try {
            novoProduto = getProduto();
            daoProduto.insere(novoProduto);
            imprimeMsg("Produto Salvo com Sucesso");
        } catch (Exception ex) {
            System.out.print("Erro ao Salvar: "+ ex.getMessage());
        }

    }//GEN-LAST:event_salvarProdutoActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        resetText();
    }//GEN-LAST:event_resetActionPerformed

    private void atualizarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarProdutoActionPerformed
        // TODO add your handling code here:
        try {
            DAOProduto daoProduto = new DAOProduto();
            boolean result = daoProduto.atualizar(getProduto());
        } catch (Exception ex) {
            System.out.println("Erro ao Atualizar: "+ ex.getMessage());
        }
    }//GEN-LAST:event_atualizarProdutoActionPerformed

    private void excluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirProdutoActionPerformed
        // TODO add your handling code here:
        DAOProduto daoProduto = new DAOProduto();
        try {
            Produto novoProduto = getProduto();
            daoProduto.apagar(novoProduto.getIdProduto());
            imprimeMsg("Produto Excluido com Sucesso");
        } catch (Exception ex) {
            System.out.print("Erro ao Atualizar: "+ ex.getMessage());
        }
    }//GEN-LAST:event_excluirProdutoActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formProduto().setVisible(true);
            }
        });
    }
    /*
     * Metodos criados 
     */
    private void resetText(){
        nomeProduto.setText("");
        codigoProduto.setText("");
        fabricanteProduto.setText("");
        precoProduto.setText("");
    }
    
    private Produto getProduto() throws Exception{
        Produto novoProduto = new Produto();
        
        novoProduto.setIdProduto(Integer.parseInt(codigoProduto.getText()));
        novoProduto.setNomeProduto(nomeProduto.getText());
        novoProduto.setFabricanteProduto(fabricanteProduto.getText());
        novoProduto.setPrecoProduto(Double.parseDouble(precoProduto.getText()));
        
        return novoProduto;
    }
    
     public void setCodigo(boolean id) throws Exception{
        int codigo = 0;
        System.out.print(id);
        if(id){
            DAOProduto daoProduto = new DAOProduto();
            ArrayList<Produto> lista = daoProduto.buscarTodos();
            Produto e = lista.get(lista.size() - 1);
            codigo = e.getIdProduto()+ 1;

        }
        codigoProduto.setText(String.valueOf(codigo));
    }
    private Produto buscarProduto(int id){        
        try {
            DAOProduto daoProduto = new DAOProduto();
            return daoProduto.buscar(id);
        } catch (Exception ex) {
            System.out.print("Erro ao Buscar Produto: "+ ex.getMessage());
        }
        return null;
    }
    

    private void imprimeMsg(String msg) {  
        JOptionPane.showMessageDialog(null, msg, "Notificação",  JOptionPane.INFORMATION_MESSAGE);  
    } 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarProduto;
    private javax.swing.JButton buscarProduto;
    private javax.swing.JTextField codigoProduto;
    private javax.swing.JButton excluirProduto;
    private javax.swing.JButton exit;
    private javax.swing.JTextField fabricanteProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nomeProduto;
    private javax.swing.JTextField precoProduto;
    private javax.swing.JButton reset;
    private javax.swing.JButton salvarProduto;
    private javax.swing.JLabel tituloProduto;
    // End of variables declaration//GEN-END:variables
}
