/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import com.sun.glass.events.KeyEvent;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Date;
import java.text.DecimalFormat;   
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sistema.de.gerenciamento.de.farmácia.Cliente;
import sistema.de.gerenciamento.de.farmácia.DAOCliente;
import sistema.de.gerenciamento.de.farmácia.DAOItemVenda;
import sistema.de.gerenciamento.de.farmácia.Produto;
import sistema.de.gerenciamento.de.farmácia.DAOProduto;
import sistema.de.gerenciamento.de.farmácia.DAOVenda;
import sistema.de.gerenciamento.de.farmácia.ItemVenda;
import sistema.de.gerenciamento.de.farmácia.Venda;

/**
 *
 * @author matheusflausino
 */
public class formVenda extends javax.swing.JFrame {

    /**
     * Creates new form formVenda
     */
    public formVenda() {
        initComponents();
        resetText();
        getCodigo();
        setTotalVenda();
        setTotalPagar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProduto = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        totalPagar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        descontoVenda = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        totalVenda = new javax.swing.JLabel();
        tipoPagamento = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        precoProduto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nomeProduto = new javax.swing.JTextField();
        buscarProduto = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        codigoProduto = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        adicionaProduto = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        codigoCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nomeCliente = new javax.swing.JTextField();
        buscarCliente = new javax.swing.JButton();
        finalizarVenda = new javax.swing.JButton();
        cancelarVender = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        qtdProduto = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setTitle("VENDA");

        tabelaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Preço/Uni", "Quatidade", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaProduto);

        jLabel1.setText("Valor a pagar");
        jLabel1.setToolTipText("");

        totalPagar.setFont(new java.awt.Font("Ubuntu", 0, 78)); // NOI18N
        totalPagar.setText("jLabel2");

        jLabel2.setText("Desconto");

        descontoVenda.setText("jTextField1");
        descontoVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                descontoVendaKeyPressed(evt);
            }
        });

        jLabel3.setText("Valor Total");
        jLabel3.setToolTipText("");

        totalVenda.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        totalVenda.setText("jLabel2");

        tipoPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dinheiro", "Cartão Crédito", "Cartão Debito", "Cheque" }));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Pagamento");

        precoProduto.setEditable(false);

        jLabel5.setText("Produto");

        nomeProduto.setEditable(false);

        buscarProduto.setText("Buscar");
        buscarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarProdutoActionPerformed(evt);
            }
        });

        jLabel8.setText("Código Produto");

        jLabel13.setText("Preço");

        adicionaProduto.setText("Adicionar Produto -->");
        adicionaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionaProdutoActionPerformed(evt);
            }
        });

        jLabel9.setText("Código Cliente");

        jLabel6.setText("Nome Cliente");

        nomeCliente.setEditable(false);

        buscarCliente.setText("Buscar");
        buscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarClienteActionPerformed(evt);
            }
        });

        finalizarVenda.setText("FINALIZAR");
        finalizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarVendaActionPerformed(evt);
            }
        });

        cancelarVender.setText("CANCELAR");
        cancelarVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarVenderActionPerformed(evt);
            }
        });

        jLabel7.setText("Quantidade");

        jButton2.setText("jButton2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(totalVenda))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(descontoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(finalizarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)
                                        .addComponent(cancelarVender, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tipoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(codigoCliente)
                                        .addGap(18, 18, 18)
                                        .addComponent(buscarCliente))
                                    .addComponent(nomeCliente)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(codigoProduto)
                                        .addGap(18, 18, 18)
                                        .addComponent(buscarProduto))
                                    .addComponent(nomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(precoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(qtdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(adicionaProduto)))))
                        .addGap(57, 57, 57)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(totalPagar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(codigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscarCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(buscarProduto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(precoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(qtdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(adicionaProduto)))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tipoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalVenda)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descontoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jButton2))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(finalizarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(cancelarVender, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(79, 79, 79))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(totalPagar)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarProdutoActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(codigoProduto.getText());
        try{
            Produto buscar = buscarProduto(id);
            nomeProduto.setText(buscar.getNomeProduto());
            codigoProduto.setText(String.valueOf(buscar.getIdProduto()));
            precoProduto.setText(String.valueOf(buscar.getPrecoProduto()));
            qtdProduto.requestFocus();
        } catch( Exception ex){
            imprimeMsg("Erro ao encontrar Produto");
        }
    }//GEN-LAST:event_buscarProdutoActionPerformed

    private void buscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarClienteActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(codigoCliente.getText());
        try{
            Cliente buscar = buscarCliente(id);
            nomeCliente.setText(buscar.getNomeCliente() );
            codigoProduto.requestFocus();
        } catch( Exception ex){
            imprimeMsg("Erro ao encontrar Cliente");
        }
    }//GEN-LAST:event_buscarClienteActionPerformed

    private void finalizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarVendaActionPerformed
        // TODO add your handling code here:
        DAOVenda daovenda = new DAOVenda();
        DAOItemVenda daoitem = new DAOItemVenda();
        Venda novaVenda = new Venda();

        try {
            novaVenda.setIdVenda(codigoVenda);
            novaVenda.setIdCliente(Integer.parseInt(codigoCliente.getText()));
            novaVenda.setDataVenda(new java.sql.Date(new Date().getTime()));
            novaVenda.setDescontoVenda(Double.parseDouble(descontoVenda.getText().isEmpty()?"0.00":descontoVenda.getText()));
            System.out.print(tipoPagamento.getSelectedItem().toString());
            novaVenda.setTipoPagVenda(tipoPagamento.getSelectedItem().toString());
            novaVenda.setTotalVenda(precoTotal);
            
            daovenda.insere(novaVenda);
            
            System.out.print(listaProduto);
            
            this.listaProduto.stream().forEach((produto) -> {
                try {
                    daoitem.insere(produto);
                } catch (Exception ex) {
                    imprimeMsg("Erro ao inserir o item: "+produto.getNomeProduto()+" no banco.");
                }
            });
            imprimeMsg("Compra finalizada com Sucesso.");
            this.dispose();
        } catch (Exception ex) {
            imprimeMsg("Erro ao inserir Venda no Banco");
        }
       
    }//GEN-LAST:event_finalizarVendaActionPerformed

    private void adicionaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionaProdutoActionPerformed
        // TODO add your handling code here:
        try{
            ItemVenda produto = getProduto();

            this.listaProduto.add(produto);

            DefaultTableModel dtm = (DefaultTableModel)tabelaProduto.getModel();
            dtm.addRow(getLinha(produto));

            setTotalVenda();
            setTotalPagar();
        }catch (Exception ex) {
            imprimeMsg("Erro ao inserir Produto");
        }finally{
            resetProduto();
            codigoProduto.requestFocus();
        }
    }//GEN-LAST:event_adicionaProdutoActionPerformed

    private void descontoVendaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descontoVendaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            setTotalPagar();
        }
    }//GEN-LAST:event_descontoVendaKeyPressed

    private void cancelarVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarVenderActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelarVenderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formVenda().setVisible(true);
            }
        });
    }
    
    private void resetText(){
        codigoCliente.setText("");
        nomeCliente.setText("");
        descontoVenda.setText("");
        resetProduto();
    }
    
    private void resetProduto(){
        nomeProduto.setText("");
        codigoProduto.setText("");
        precoProduto.setText("");
        qtdProduto.setText("");
    }
    
    public static byte[] gerarHash(Date dataHora) {
        try {
            MessageDigest md = MessageDigest.getInstance("MD5");
            md.update(dataHora.toString().getBytes());
            return md.digest();
        } catch (NoSuchAlgorithmException e) {
            return null;
        }
      }
    private static String stringHexa(byte[] bytes) {
        StringBuilder s = new StringBuilder();
        for (int i = 0; i < bytes.length; i++) {
            int parteAlta = ((bytes[i] >> 4) & 0xf) << 4;
            int parteBaixa = bytes[i] & 0xf;
            if (parteAlta == 0) s.append('0');
            s.append(Integer.toHexString(parteAlta | parteBaixa));
        }
        return s.toString();
     }
    
    private void getCodigo(){
        this.codigoVenda = stringHexa(gerarHash(new Date()));
    }
    
    private ItemVenda getProduto() throws Exception{
        ItemVenda produto = new ItemVenda();
        
        produto.setIdProduto(Integer.parseInt(codigoProduto.getText()));
        produto.setIdVenda(this.codigoVenda);
        produto.setNomeProduto(nomeProduto.getText());
        produto.setPrecoProduto(Double.parseDouble(precoProduto.getText()));
        produto.setQtdProduto(Integer.parseInt(qtdProduto.getText()));
        
        return produto;
    }
                
    private Object[] getLinha(ItemVenda produto){
        return new Object[]{produto.getNomeProduto(), 
                            produto.getPrecoProduto(), 
                            produto.getQtdProduto(),
                            produto.getQtdProduto()*produto.getPrecoProduto(),                            
                };
    }
    
    private void setTotalVenda(){
        DecimalFormat df = new DecimalFormat("0.##");
        int n = tabelaProduto.getRowCount();
        Double preco = 0.0;
        
        for (int i = 0; i < n; i++)
            preco +=  Double.parseDouble(tabelaProduto.getValueAt(i, 3).toString());
        
        this.precoTotal = preco;
        
        totalVenda.setText(df.format(this.precoTotal));
    }
    
    private void setTotalPagar(){
        DecimalFormat df = new DecimalFormat("0.##");
        double desc = 0;
        
        if(descontoVenda.getText().contains("%")){
            double perc = Double.parseDouble(descontoVenda.getText().replace("%", ""));
            desc = this.precoTotal*(perc/100);
        }else if(!descontoVenda.getText().isEmpty()){
            desc = Double.parseDouble(descontoVenda.getText());
        }
        
        if(desc <= this.precoTotal)
            totalPagar.setText(df.format(this.precoTotal - desc));
        else
            imprimeMsg("Descoto maior que o total. WTF??");
    }
    
    private Produto buscarProduto(int id){        
        try {
            DAOProduto daoProduto = new DAOProduto();
            return daoProduto.buscar(id);
        } catch (Exception ex) {
            System.out.print("Erro ao Buscar Produto: "+ ex.getMessage());
        }
        return null;
    }
    
    private Cliente buscarCliente(int id){        
        try {
            DAOCliente daoCliente = new DAOCliente();
            return daoCliente.buscar(id);
        } catch (Exception ex) {
            System.out.print("Erro ao Buscar Cliente: "+ ex.getMessage());
        }
        return null;
    }
    
    private void imprimeMsg(String msg) {  
        JOptionPane.showMessageDialog(null, msg, "Notificação",  JOptionPane.INFORMATION_MESSAGE);  
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionaProduto;
    private javax.swing.JButton buscarCliente;
    private javax.swing.JButton buscarProduto;
    private javax.swing.JButton cancelarVender;
    private javax.swing.JTextField codigoCliente;
    private javax.swing.JTextField codigoProduto;
    private javax.swing.JTextField descontoVenda;
    private javax.swing.JButton finalizarVenda;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomeCliente;
    private javax.swing.JTextField nomeProduto;
    private javax.swing.JTextField precoProduto;
    private javax.swing.JTextField qtdProduto;
    private javax.swing.JTable tabelaProduto;
    private javax.swing.JComboBox<String> tipoPagamento;
    private javax.swing.JLabel totalPagar;
    private javax.swing.JLabel totalVenda;
    // End of variables declaration//GEN-END:variables
    private double precoTotal = 0.00;
    private String codigoVenda;
    ArrayList<ItemVenda> listaProduto = new ArrayList();
}
